### ISSUE TITLE
[FEATURE] Periodically reapply OCTune settings.

### ISSUE THREAD

**Issue by isral** [nicehash/NiceHashQuickMiner#566] opened 2021-06-11 05:14 UTC
**Is your feature request related to a problem? Please describe.**
OCTune setrings randomly unapplied.

**Describe the solution you'd like**
Every minute, reapply OCTune settings (Classic method for overclocking and Fan Management).

**Describe alternatives you've considered**
Fix the bug #44 .
Even if the bug fixed, this feature still needed for safety reason.

**Additional context**
v0.5.1.3
GTX 1660
Windows 10 64 bit

**Comment by Dohtar1337** [comment] 2021-08-12 09:08
Are there any other overclocking tools opened like MSI afterburner? Please send us logs

**Comment by isral** [comment] 2021-08-12 10:23
No other overclocking tools.
I post the log at the end of #44

**Comment by Dohtar1337** [comment] 2021-08-12 11:05
Does this still happen? Note that OC settings will get set to default while the DAG is being generated. This is expected behaviour. Once this is done, the OC settings should go back to normal.

Please check if the same happens when using alternate overclock method instead of classic one.

**Comment by isral** [comment] 2021-08-13 09:43
I think it's not happened using Alternative method for overclocking.

**Comment by Dohtar1337** [comment] 2022-07-14 10:38
Obsolete. Will not implement or will the issue is to old. Closing.

**Closed by Dohtar1337** 2022-07-14 10:38 UTC
Labels: enhancement
