### ISSUE TITLE
OC Tune: Failed to set core uvolt, reason: -11

### ISSUE THREAD

**Issue by N0rdmann** [nicehash/NiceHashQuickMiner#238] opened 2021-03-19 04:10 UTC
When trying to undervolt my 3080, e.g. just from 725mV to 720mV i get the following error in cmd output
`[0x00003518][warning] device #0 | Failed to set core uvolt, reason: -11

> Events:
> [19.3.2021, 05:08:10] Applied OC (alt) successfully
> [19.3.2021, 05:08:10] Applying undervolt: 720 mV
> [19.3.2021, 05:08:10] Applying OC (alt) dev=0 max core=1110 memory=10500

**Comment by nicehashdev** [comment] 2021-03-20 22:18
I have noticed similar issues myself, will def. look into this and will be fixed for next version.

**Comment by nicehashdev** [comment] 2021-03-20 22:38
I have checked this issue and here are the findings: The issue is that you cannot go any lower. NVIDIA drivers do not permit lower voltage than this. For all ampere cards this limit is between 0.70 and 0.75 V, depending on the card itself.

**Comment by N0rdmann** [comment] 2021-03-21 03:06
Thx for the fast response!
I also couldn't bring the card lower than 725 even with MSI Afterburner

**Closed** 2021-03-23 19:03 UTC
Labels: bug, resolved

**Comment by JoelBonetR** [comment] 2022-05-15 20:29
I face the same issue with a 3080 ti FE, but it also brings me the same error even trying to set a higher voltage (did it just for testing). I tried 800mv and `device #0 | Failed to set core uvolt, reason: -11` still persists.

It's at 750mv according to OCTune.
