### ISSUE TITLE
Mobile chips; 0.3.2.2 Could not obtain power consumption

### ISSUE THREAD

**Issue by Tyberious** [nicehash/NiceHashQuickMiner#75] opened 2021-02-21 10:50 UTC
I was previous on the 0.3.0.2 version and switched to the 0.3.2.2RC and power consumption no longer reads on mobile series chips such as 1070 and 2070MaxQ.  It does still work on desktop variants however.

**Comment by nicehashdev** [comment] 2021-02-21 15:36
There is no guarantee that mobile devices will work as they are not officially supported. You may try experimenting with drivers and see if that helps in any way.

**Comment by Tyberious** [comment] 2021-02-21 20:27
> There is no guarantee that mobile devices will work as they are not officially supported. You may try experimenting with drivers and see if that helps in any way.

Yes I understand that.  I am simply reporting that between 0.3.0.2 and 0.3.2.2 power consumption was broken for mobile devices.

**Comment by nicehashdev** [comment] 2021-02-21 21:15
It is not a bug because as said, mobile devices are not officially supported. If they work, fine, but if they don't we arent looking into it. Mining with laptops is not a good idea at all and we do not recommend it.

**Comment by Tyberious** [comment] 2021-02-21 21:23
Mining with laptops is perfectly safe, in fact 2070 MaxQ based laptops perform better than a desktop 2060 at nearly half the power.  Mining on a laptop is no different than playing games 24/7 and in fact is not as hard on them due to no CPU load.

Also, I am not asking you to support anything specific just wondering why it reported power use correctly and now simply doesn't at all.  It still mines as it did and temperature is reported just not power consumption.  I would be more than happy to fix it myself but its closed source.

**Comment by nicehashdev** [comment] 2021-02-22 21:49
You can try to play around with drivers. Try GeForce compared to DCH drivers. I have noticed that some features are not available on GeForce drivers but are available on DCH drivers. Perhaps that will solve your issue.

**Comment by dvv47** [comment] 2021-02-23 16:12
Same for me, laptop 2070 max q, DCH driver 461.51
for version 0.3.0.2 everything works
and for latest version - no

**Comment by nicehashdev** [comment] 2021-02-23 16:47
Do you get only warning about not being able to get power consumption, but mining works? Or you also have problem with mining itself?

**Comment by dvv47** [comment] 2021-02-23 17:24
@nicehashdev only warning about power consumption

**Comment by nicehashdev** [comment] 2021-02-23 18:04
That is good then. It still works and mines. As I said, try to experiment with different versions of drivers. It may solve the problem.

**Comment by MythB** [comment] 2021-02-23 18:28
same here laptop RTX2060 DCH v461.40 also hashrate not shown on console but shown in system tray icon

**Comment by chrisngrod** [comment] 2021-02-23 18:43
Same "version 0.3.0.2 everything works".

I've tried what I think is every driver that was available for a 3080.

Speed is around 55MH and temp at 56 degrees so I'm not overly concerned.

**Comment by takeruadelbert** [comment] 2021-02-24 04:52
Hi @nicehashdev I encounter the same problem with RTX 2060.
However it works properly when I am using **_v0.3.0.6_RC_**, the problem perists on **_> 0.3.0.6_RC_** (including latest stable release which is _v0.3.2.6_)

**Comment by nicehashdev** [comment] 2021-02-25 16:40
Please, [check here](https://github.com/nicehash/NiceHashQuickMiner/issues/94) for possible solution, closing this as duplicate.

**Closed by nicehashdev** 2021-02-25 16:40 UTC
Labels: bug, enhancement
