### ISSUE TITLE
[FEATURE] Auto set windows page file

### ISSUE THREAD

**Issue by amore514** [nicehash/NiceHashQuickMiner#451] opened 2021-04-24 17:44 UTC
It would be great to have an option to auto-set the windows page file depending on the cards detected. If new cards are added this would change the page file accordingly.

**Comment by nicehashdev** [comment] 2021-05-07 20:43
I am currently investigating possibility of getting rid of the necessity of having large page file in Windows. Latest drivers expose a lot more various parameters, but due to bad documentation, it is hard to find what needs to be done. I did manage to have some success with Tesla cards - extra host memory did not need to be committed for successful allocation of memory on device.

**Comment by amore514** [comment] 2021-05-07 21:14
My workaround was to install a 2nt HD and dedicate the entire drive to a page file. Now as I grow cards I won't have to mess with this, lol. But I am a bit more advanced than a few people in school using your software and they all struggle with this part. eliminating this would be great but as a workaround adding an option to auto set the page file would help a lot of people.

**Comment by amore514** [comment] 2021-05-07 21:15
On that note, eliminating "Windows" would be a better option :-)

**Comment by nicehashdev** [comment] 2021-05-08 07:08
Yes, so far, if you dont need display and have a high end GPU (titan), you can put it in TCC mode and there is no extra allocation in host memory.

**Comment by Dohtar1337** [comment] 2022-07-14 10:40
Obsolete. Will not implement, resolved or will the issue is too old. Closing.

**Closed by Dohtar1337** 2022-07-14 10:40 UTC
Labels: enhancement, reviewing
