### ISSUE TITLE
Release 0.4.0.0RC immediately freezes my PC

### ISSUE THREAD

**Issue by hapklaar** [nicehash/NiceHashQuickMiner#129] opened 2021-03-03 14:52 UTC
When the new Excavator 1.6.5a_Build_963 starts, it immediately hangs my PC. Both my monitors turn black and PC is no longer responding. Need to turn it off by holding the power button.

Have been using the previous RC's without issue.

Using Windows 10 with RTX3090 and latest NVidia drivers.

**Comment by Swiftnc** [comment] 2021-03-03 15:01
Release 0.4.0.0RC also immediately causes my screen to go black and the computer to not respond to anything.  Upgraded from previous release.  All reboots led to same issue until I was able to quickly kill off the QuickMiner Task Schedule autostart.  Windows 10 20H2 x64 fully patched with Nvidia 3080 and Nvidia drivers 461.72.  You should pull this release until the cause is found.

**Comment by nicehashdev** [comment] 2021-03-03 15:24
Are you perhaps using old oc_profiles that still have fan parameter inside? Because that one is now replaced with mV for undervolting. It is possible that your PC crashes because GPU gets too little VCORE. 

Delete your old oc profiles and you should be fine.

**Comment by nicehashdev** [comment] 2021-03-03 15:38
You are right. There is a major bug. Luckily we have these RC versions :) so majority of miners are not affected. Thanks for testing and letting me know. Fix will be up in few minutes.

**Comment by Swiftnc** [comment] 2021-03-03 16:10
Glad to help!  Thanks for looking into this so quickly.

**Comment by hapklaar** [comment] 2021-03-03 16:23
> Are you perhaps using old oc_profiles that still have fan parameter inside? Because that one is now replaced with mV for undervolting. It is possible that your PC crashes because GPU gets too little VCORE.
> 
> Delete your old oc profiles and you should be fine.

Is this still required, or will the old profiles continue to work/be converted in the fixed release?

**Comment by nicehashdev** [comment] 2021-03-03 17:06
Fixed now.

Regarding profiles; there is no autoconversion, but if the values are completely off - such as, when doing profile with vcore, you need core clock 500+, and nobody has delta core +500 - so nothing bad should happen, just refusal for command to be executed due to invalid parameters.

**Comment by hapklaar** [comment] 2021-03-03 17:25
Can confirm, new release works fine. Did not have to delete any OC profiles.

**Comment by Swiftnc** [comment] 2021-03-03 18:59
New release works for me.  Thanks!

**Comment by nicehashdev** [comment] 2021-03-03 20:34
Okay, this bug is fixed. Closing.

**Closed by nicehashdev** 2021-03-03 20:34 UTC
Labels: bug, done, question
