### ISSUE TITLE
[FEATURE] MQTT Publishing for GPU stats/Mining Stats

### ISSUE THREAD

**Issue by Lollitoe** [nicehash/NiceHashQuickMiner#632] opened 2021-08-20 10:52 UTC
If we could have MQTT publishing made available that would be pretty awesome for custom dashboards and integration into a variety of systems.

Parameters to be exposed to MQTT

GPU ID | GPU Name | MinKT | AvgKT | UMedKT | HWerr | HWok | CoreDelta | MemDelta | PowerLim (W) | TDPLim (%) | PowerReal (W) | Speed(MH/s) | Eff. (kH/J)

GPU ID | GPU Name | Temperature(℃) | Utilization(%) | Fan(RPM) | Fan level | Fan settings | Core(MHz) | Core Limit(MHz) | Core Volt.(mV) | Memory(MHz)

**Comment by sparkiesweden** [comment] 2021-08-22 08:01
+1

**Comment by Dohtar1337** [comment] 2022-07-14 10:38
Obsolete. Will not implement or will the issue is to old. Closing.

**Closed by Dohtar1337** 2022-07-14 10:38 UTC
Labels: enhancement
