### ISSUE TITLE
[BUG]  After about half an hour of use, quickminer's performance collapses with 3060ti card

### ISSUE THREAD

**Issue by fradem72** [nicehash/NiceHashQuickMiner#910] opened 2022-06-24 06:58 UTC
*I have had this problem since I started mining in December 2021 but in recent months I had solved it by opening a ps2 emulator together with Quickminer and this thing worked until a couple of days ago
but now the problem has come back>
after about 30 min where quickiner works regularly set to high optimization and undermines around 60 mhs of speed, it collapses and stops at 37 ... the watts from about 130 croill to about 97 and there is no c-e- way to get it back up at less that I do not reset the pc and is another half hour at 60 and then roll back to 36/37. what can i do to solve?
what can it depend on? please help me

this issue is in every version i tried to install, BOTH FOR QUICKMINER AND NVIDIA DRIVERS

**NVIDIA driver version**
512.17

**Hardware**
3060 ti lhr
intel core i5 11600k processor
16gb RAM DDR4

**Comment by fradem72** [comment] 2022-06-25 12:06
noone has some ideas or suggestions on it?

**Comment by elmajdal** [comment] 2022-07-03 07:19
The same is happening with me . I have 3060ti and this is happening as well. 

I have multiple other Rigs like 3090 and 3080ti 1080ti 

But the only rig not stable with quickminer is 3060ti 

If anyone needs logs to send am ready to send for analysis 

By the way if I worked with the stable version which is not RC , then the rig is stable

**Comment by Dohtar1337** [comment] 2022-07-14 10:12
Does the issue persist with the latest 0550 release?

**Comment by elmajdal** [comment] 2022-07-14 11:02
> Yes Still.

Any version After 0.5.3.6 is not stable.

0.5.3.6 works perfectly, i tried all RC versions and also 0.5.5.5.0 , however, Quickminer Excavator keeps restartings or even crash the machine and restarts or leads to BSOD

**Comment by Dohtar1337** [comment] 2022-07-15 10:23
Do you use the installed version?

Please try uninstalling it completely and run the installer again.

please let me know if this fixed the issue.

**Comment by elmajdal** [comment] 2022-07-16 23:16
> Do you use the installed version?
> 
> Please try uninstalling it completely and run the installer again.
> 
> please let me know if this fixed the issue.

I even formatted the machine mutliple times.

and Yes i use the installed version.

There is an issue wit the 3060Ti cards. 

I have multiple rigs with 3080 Ti, 3090 

the only issue is with the 3060 Ti cards.

**Comment by asakiasako** [comment] 2022-07-18 04:22
I might have the same problem. After I updated to the latest versions, my rig sometimes crashes with 3060ti. 
But it didn't happen when I was using 0.5.3.6
It also do not happen to my other rigs without 3060ti.
I tried recovering windows system files and diagnose hardware but didn't fix it.

**Comment by Dohtar1337** [comment] 2022-07-20 06:24
Stop the mining first and edit the nhqm.conf

In the line with the command 'launcheCommandLine' , add the -CLS

"launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",

Start the mining again and the -CLS will be seen in the excavator console.

**Comment by elmajdal** [comment] 2022-07-21 10:13
24 hours passed and with the new line changes "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",


version 0.5.5.5.0 is stable .

i will update after 72 if still stable.

**Comment by fradem72** [comment] 2022-07-21 11:02
For my info: what is the function of -CLS in command line?

Il gio 21 lug 2022, 12:13 ElMajdal ***@***.***> ha scritto:

**Comment by elmajdal** [comment] 2022-07-21 11:09
> "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",

FEATURE - The LHRv3 unlock system has two algorithms: the first leading to a faster hash rate and the second being more stable. The default algorithm is the fastest one, switch to the more stable one can be achieved by using "-CLS" in the Excavator command line.

**Comment by fradem72** [comment] 2022-07-23 15:26
it seems it finally works properly!

**Comment by elmajdal** [comment] 2022-07-24 13:37
> 24 hours passed and with the new line changes "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",
> 
> version 0.5.5.5.0 is stable .
> 
> i will update after 72 if still stable.

72 hours passed and the rig is stable with version 0.5.5.5.0 after applying  -CLS

**Comment by asakiasako** [comment] 2022-07-27 16:50
> > Stop the mining first and edit the nhqm.conf
> 
> > 
> 
> > In the line with the command 'launcheCommandLine' , add the -CLS
> 
> > 
> 
> > "launchCommandLine" : "-qx -qm -d 2 -f 6 -CLS",
> 
> > 
> 
> > Start the mining again and the -CLS will be seen in the excavator console.
> 
> 
> 
> This recipe didn't work for me. I try nhqm 0.5.5.0 with "-CLS" and nvdr 512.77 and system crashed like before.

Same for me. I'm stable with 0.5.4.0, the version after that is not stable.

**Comment by DEF29** [comment] 2022-07-29 00:44
I recommend everyone to try v0.5.5.1 RC
I uninstalled v0.5.5.0 and installed v0.5.5.1 RC and the system became more stable. However, version 0.5.5.1 RC did not resolve the BSOD issue after I quit the NHQM program or just stopped mining. I'll post later how testing goes.

**Comment by DEF29** [comment] 2022-07-29 13:43
36 hours passed since I started using v0.5.5.1 RC.
**While mining is going on**, the system has never collapsed. The system is stable. I hope that the issue is resolved positively.

However, version 0.5.5.1 RC did not resolve the BSOD issue after I quit the NHQM program or just stopped mining.

**Comment by ybop** [comment] 2022-08-03 07:14
I'm using v5.5.1 RC and my 3060ti cards are crashing after a few hours.  It gets stuck in a loop whereby it says already running, closing in x seconds.

**Comment by ybop** [comment] 2022-08-04 02:36
I have done some testing.  

1. Running NHQM with the medium profile set in rig manager but not not actually mining.  Just running it to set the clock speeds.
2. Next I run NBMINER to miningpoolhub and getting similar or slightly better hashrates but more importantly rock solid stable.

With identical clock settings, PC crashes after 30 to 300 minutes using NHQM.  My rigs are as follows:

1. 3070ti
2. 3060ti
3. 3060ti
4. 3060ti
5. 3060ti
6. 3060ti
7. 1070ti
8. 1070ti

Using NHQM 0.5.5.1 RC with -CLS 

Also, if mining with NHQM and I try to stop it, it will get stuck closing and sometimes it will BSOD.

So I think there is an issue with NHQM and 3060ti cards.

I will download nicehash miner and test NBMINER with that.  I really like NHQM and will change back when it's fixed.

**Comment by tjayz** [comment] 2022-08-06 02:33
> Same for me. My rig is stable with 0.5.4.0, the version after that is not stable.

Something definitely changed after this version. Hashrates bleed erratically as watts bounce all over the place and 3060ti rigs highly unstable. Best you can get after massive tweaking is just excavator restarting. Please put whatever is in this version back into the latest version and allow us to set manually if we want to use lhrv3 unlock for our cards if this can not be automatically deciphered by the miner. Much appreciated.

**Comment by ybop** [comment] 2022-08-06 03:15
Currently running NHQM with mining stopped (just to set the clocks) and nicehash miner using the NBMINER plugin everything set to only mine daggerhashimoto and rigs are doing fine.  On the rare occasion there is a problem, NBMINER simply restarts and all good again.  The main problem with NHQM and 3060ti cards is when it crashes, it is unable to recover.  Either BSOD or gets stuck in an endless loop saying something like already running, closing in x seconds.  Fixing crash recovery should be the first priority and then improving stability to match NBMINER.

**Comment by DEF29** [comment] 2022-08-07 12:25
ybop, use NHQM 0.5.5.1 RC in **optimization** mode and then you probably will not have system crashes. I have 2 cards of 3060 TI and 3 cards of 3070 TI in my rig and system is stable now.

When you switch to optimization mode, use manual overclocking settings for your video card model from this article:
https://www.nicehash.com/blog/post/nvidia-and-amd-graphics-card-oc-settings-for-mining

Optimization mode allows you to achieve low power consumption and at the same time maintain a high hashrate.

Also do not forget that Chinese PSUs should not be loaded more than 65%. This will avoid overload protection (unexpected stop of the PSU), heating of the PCI-E connectors at the points of connection to the video card and inside the PSU itself, which in the end can lead to a FIRE.

**Comment by DEF29** [comment] 2022-08-07 12:33
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/37115984/183290620-6a474773-801d-41be-a983-62df1cc00216.png">

 It is my case on NHQM 0.5.5.1 RC in optimization mode. It works fine for about 10 days without BSOD and any crashes.

**Comment by ybop** [comment] 2022-08-07 12:34
> ybop, use NHQM 0.5.5.1 RC in **optimization** mode and then you probably will not have system crashes.

I have run it in optimization mode and done a lot of tinkering with the clocks and voltages but the instability continues. The fact that it is stable with NBMINER but not excavator shows there is a problem with the latter which hopefully will be fixed.

I use Silverstone ST1500ti power supplies loaded under 80%  I have also customised pcie power cables (16AWG), much more reliable than stock.

I've been mining 5+ years and am well aware of the pitfalls and potential failure points.  I love NHQM and look forward to going back to it when it's stable.

**Comment by DEF29** [comment] 2022-08-07 12:40
I have included the screenshot above, check it out

imho 80% is too much

in your case, there may be a revision of the video card with memory, which is not stable during rapid heating

**Comment by ybop** [comment] 2022-08-07 12:49
You are using a lot more juice than I am.  My 3060ti's run stable using around 130 to 140 watts and 61 MH/s with NBMINER.  

80% is totally fine, especially with a quality power supply.  The main issue actually isn't that it crashes after a few hours, it's that it fails to recover.

I have tested everything and the final proof that my setup isn't faulty is seeing NBMINER running fine where NHQM crashes and gets stuck in an endless loop.  Clearly there is something NHQM is doing differently that is causing this.

**Comment by elmajdal** [comment] 2022-08-09 13:44
> 

tried you suggestion as seen below, working properly, also noticed NiceHash miner name the cards in their model ! NHQM does not have this option !

<img width="1504" alt="Screen Shot 2022-08-09 at 4 41 57 PM" src="https://user-images.githubusercontent.com/108606617/183664831-ece49ed7-12c6-463c-97d7-540b41c9c8c1.png">

**Comment by Dohtar1337** [comment] 2022-09-27 09:17
Does the issue still persist with the latest version?

**Comment by fradem72** [comment] 2022-09-27 09:21
With -cls command I solved...but the issue now is that from 0.00006500
average per day I cannot go over 0.00001050 per.day🥺

Il mar 27 set 2022, 11:17 Dohtar1337 ***@***.***> ha scritto:

**Comment by Dohtar1337** [comment] 2022-10-24 11:25
Solved

**Closed by Dohtar1337** 2022-10-24 11:25 UTC
Labels: bug
