### ISSUE TITLE
[FEATURE] make task icon 'light theme friendly'

### ISSUE THREAD

**Issue by Jurgen1980** [nicehash/NiceHashQuickMiner#508] opened 2021-05-11 10:56 UTC
**Is your feature request related to a problem? Please describe.**
The icon is almost not visabel when light theme is enabled on the windows task bar

**Describe the solution you'd like**
Give the icon a fine black/dark border?

**Describe alternatives you've considered**

**Additional context**

**Comment by Dohtar1337** [comment] 2022-07-14 10:39
Obsolete. Will not implement, resolved or will the issue is too old. Closing.

**Closed by Dohtar1337** 2022-07-14 10:39 UTC
Labels: enhancement, reviewing
