### ISSUE TITLE
Failed to get power limits

### ISSUE THREAD

**Issue by kelthar** [nicehash/NiceHashQuickMiner#157] opened 2021-03-07 21:22 UTC
When I QuickMiner on my Gigabyte 1660 Super I get this error message. Running it as admin, not using Afterburner.

Quickminer: **0.4.0.3 RC**
Using: 461.40
OS: Windows 10 x64
Running it headless and remote in

[16:33:31][0x00002538][warning] device #0 | Failed to get power limits (issue with NVIDIA drivers!)
...
[16:37:31][0x00001f98][info] core | Device #0-0 speed: 31.25 MH/s power: -3.00 W efficiency: -10416947.200000 H/J

**Comment by gigaplex** [comment] 2021-03-09 11:35
I get the same problem with my MSI 3070 Gaming X Trio with the 461.72 drivers. While in this state, OCTune also cannot set the power limit. Rolling back to 460.89 drivers resolved the issue.

**Comment by nicehashdev** [comment] 2021-03-09 19:11
The issue can be in NVIDIA drivers or simply you have a device that does not support this feature (typical for laptops).

**Comment by gigaplex** [comment] 2021-03-09 21:06
> The issue can be in NVIDIA drivers or simply you have a device that does not support this feature (typical for laptops).

Both the reports in this issue so far are desktop cards, and my one does work on older drivers. Something in the newer driver broke compatibility with NiceHash. Afterburner is still able to set the power limit though so the new driver is still capable of the functionality.

**Comment by nicehashdev** [comment] 2021-03-09 21:43
Afterburner uses private part (not available for public) of NVAPI to work with this, which is far more reliable than NVML that was made for public by NVIDIA. I am working on RE these parts, but the process is slow. I have managed to get limits but consumption in W yet, so the code is still half dependent on NVML. Until then, this is going to be issue on some systems. You may try to replace nvml DLL from older driver to the newer one, perhaps that solves the issue.

**Comment by gigaplex** [comment] 2021-03-09 23:00
> Afterburner uses private part (not available for public) of NVAPI to work with this, which is far more reliable than NVML that was made for public by NVIDIA. I am working on RE these parts, but the process is slow. I have managed to get limits but not the consumption in W yet, so the code is still half dependent on NVML. Until then, this is going to be issue on some systems. You may try to replace nvml DLL from older driver to the newer one, perhaps that solves the issue.

As long as you can replicate the issue, I'm happy to wait for a fix rather than try to work around by mixing DLLs. The reason I wanted to upgrade the driver was to fix the memory leak in NVML, but replacing the DLL is likely to reintroduce the leak.

**Comment by nicehashdev** [comment] 2021-03-11 03:21
Okay, I have managed to RE enough to get all power related data through NVAPI and bypassed NVML. Here is the new Excavator which has this feature: https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.4.1.2_RC/excavator_b723.zip

Please, try it out. Thanks!

**Comment by gigaplex** [comment] 2021-03-11 03:41
Replacing the stable branch binary with that build appears to work fine on the older driver. I'll try again later on the newer driver to see if the issue is resolved there. Are there any specific things you want me to test, and should I be using the stable or RC branch of QuickMiner as the baseline?

Would you expect the memory usage of excavator to keep climbing while the OCTune page is still open with this new build? I'd expect the nvmlDeviceGetPowerUsage memory leak to disappear if you're no longer calling that method. I'm still seeing the memory usage climb.

**Comment by nicehashdev** [comment] 2021-03-11 04:16
This is something I expected to get solved too yes, but unfortunately, the bug appears to be deeper inside some of NVIDIA libs, probably nvapi64.dll (which is being used now directly for power management).

Everything should work now. Getting current power consumption, setting power limits for TDP etc..

**Comment by gigaplex** [comment] 2021-03-11 04:29
Looks like it's working fine on the newer driver now too. Memory usage still increases with the new driver and OCTune, so it doesn't appear the new driver fixes that.

**Comment by nicehashdev** [comment] 2021-03-11 04:52
You don't have to leave OCTune open, just open it when you wanna check something, otherwise, keep it closed.

**Comment by nicehashdev** [comment] 2021-03-11 11:32
Resolved in upcoming version, closing.

**Closed by nicehashdev** 2021-03-11 11:32 UTC
Labels: done, question
