### ISSUE TITLE
[BUG] Optimisation profiles resulting in crashing on 2xGTX 1080 after updating to latest non-DCH drivers

### ISSUE THREAD

**Issue by munaknif** [nicehash/NiceHashQuickMiner#380] opened 2021-04-13 03:02 UTC
**Describe the bug**
2xGTX 1080s crashing on anything other than Lite/ Efficient Low after updating to recommended drivers after previously ascertaining 34-35MH/s on High on older DCH driver.

**To Reproduce**
Steps to reproduce the behaviour:
1. Update to Nvidia 465.89 non-DCH driver
2. Run QuickMiner v0.4.5.5 or up
3. Select Medium/High/ Efficient Optimisation
4. Immediately crash

**Expected behavior**
For QuickMiner to ascertain the same hashrate as prior to updating my drivers but hopefully without the crashing every few hours caused by older DCH drivers.

**Version affected (please complete the following information):**
 - v0.4.5.5 STABLE 
 - v0.4.7.1 RC

**Hardware**
2x MSI Geforce GTX 1080 Gaming X 8G, connected directly to motherboard via PCI-E Gen3

**Logs**
[exported_logs.zip](https://github.com/nicehash/NiceHashQuickMiner/files/6300944/exported_logs.zip)

**Additional context**
I was previously mining at around 34-35MH/s per card on both GTX 1080s with High Optimisation on DCH 461.72 drivers. Updated my drivers to the ones recommended here as after a few hours of mining on the previous drivers, my drivers were crashing.
Tried mining on STABLE v0.4.5.5, drivers immediately crash on anything other than Lite/ Efficient Low. Tried mining on RC v0.4.7.1, same results.
Attempted following the guide (https://github.com/nicehash/NiceHashQuickMiner/issues/315) word for word, same result. Attempted tooling around with settings in Profile Inspector, same result.

**Comment by nicehashdev** [comment] 2021-04-13 03:15
OC instability is not a bug and will not be resolved. There is nothing that can be done from my side to improve overclockability of your chip. Closing.

**Closed by nicehashdev** 2021-04-13 03:15 UTC
Labels: optimization, question, resolved

**Comment by munaknif** [comment] 2021-04-13 03:20
Did you actually read the post? I'd been able to achieve 34-35MH/s through the High optimisation profile, now I'm not even getting 30MH/s because I can't use most of the optimisation profiles after a driver update. My chip's overclockability on a hardware level doesn't seem to be the issue here.

**Comment by nicehashdev** [comment] 2021-04-13 03:27
That is an issue you may address NVIDIA with.

You can always adjust your own OC.

1080 are very special card and each one needs different numbers. You will have to play around with numbers to achieve good results.

**Comment by munaknif** [comment] 2021-04-13 03:55
If anyone else somehow manages to come across this issue, the solution was to install the older non-DCH driver 461.72. Not sure why but for some reason the newest driver and QuickMiner's optimisation profiles don't seem to get along with each other in this specific case. Now back up to getting 33-34MH/s per card with the medium optimisation profile.
