### ISSUE TITLE
[FR] Ability to apply profiles based on time (scheduling)

### ISSUE THREAD

**Issue by Hukuma1** [nicehash/NiceHashQuickMiner#252] opened 2021-03-21 00:47 UTC
Feature Request

Right now we have a game profile. And I read that more profiles are coming. This is great to hear! Can we also please implement a way to schedule specific profiles to be applied at specific times?

For example: 
-run AGGRESSIVE profile [100% fans + heavy overclock] from 8am to 11pm
-run QUIET profile [60% fans + moderate overclock] from 11:01pm to 7:59am

This would help some people sleep better. Speaking from experience. ;)

**Comment by nicehashdev** [comment] 2021-03-23 20:33
There are more profiles planned, including custom ones, but not sure how far we will go with this. If there is big demand for timed profiles, we will implement them. I will leave this issue open so that other users who wish to have this feature implemented can report their vote here.

**Comment by Hukuma1** [comment] 2021-03-23 23:17
Would it work with Windows Task Scheduler? Is that as simple as running QuickMiner with command line --profile1, --profile2, etc switches?

**Comment by nicehashdev** [comment] 2021-03-24 01:59
Unfortunately no. We will introduce some easy way if we decide to make this.

**Comment by ItzSilvx** [comment] 2021-03-24 16:01
I would love to see this feature aswell.

**Comment by alexbaucom17** [comment] 2021-04-01 03:13
I would also love to see something like this. For my use case, even a way to automatically schedule mining to start and stop would be a huge plus if that is an easier first step to take. I have tried doing something like that with the Windows Task Scheduler, but have been unsuccessful in getting it to work, so an easier way to do some basic scheduling would be much appreciated.

**Comment by kizza42** [comment] 2021-04-18 00:04
Would love a way to have a scheduled task disable gaming mode if I accidentally left it on and went to bed.

**Comment by Alamer1** [comment] 2021-04-20 10:51
would love to see this implemented

**Comment by mikeschat** [comment] 2021-04-22 07:26
Would love to see this. I run different optimization profiles at night and during the day too.

**Comment by YF974** [comment] 2021-07-22 15:42
bonjour effectivent , pouvoir planifié l'arret et le redemarage a une heure specifiques , pour effectuer les mises a jours automatiques de windows ,serai bien venu merci

**Comment by Dohtar1337** [comment] 2022-07-14 10:42
Obsolete. Will not implement, resolved or will the issue is too old. Closing.

**Closed by Dohtar1337** 2022-07-14 10:42 UTC
Labels: enhancement, reviewing
