### ISSUE TITLE
[FEATURE] enable/disable game mode with double click on task icon.

### ISSUE THREAD

**Issue by Jurgen1980** [nicehash/NiceHashQuickMiner#507] opened 2021-05-11 10:53 UTC
**Is your feature request related to a problem? Please describe.**
atm it's unhandy to enable or disable gaming mode

**Describe the solution you'd like**
Make a hotkey or double click on icon to enable or disable gaming mode.
This can also be a shortcut on desktop.

**Describe alternatives you've considered**

**Additional context**

**Comment by Dohtar1337** [comment] 2022-07-14 10:39
Obsolete. Will not implement, resolved or will the issue is too old. Closing.

**Closed by Dohtar1337** 2022-07-14 10:39 UTC
Labels: enhancement, reviewing
